artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  feature_store_dir: artifacts/data_ingestion/feature_store
  download_path: artifacts/data_ingestion/dataset.zip
  data_download_url: https://drive.google.com/file/d/17EWBxoGZyUvEPKGtht-4ZGa69jyOuNz-/view?usp=drive_link

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ["train", "test", "valid", "data.yaml"]

model_training:
  root_dir: artifacts/model_training
  model_path: artifacts/model_training/detection_n.pt
  trained_model_url: https://drive.google.com/file/d/13Y40l1az1yjfSgtyHHFfLNY-mOVL5b9T/view?usp=drive_link
