artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  feature_store_dir: artifacts/data_ingestion/feature_store
  data_download_url: https://drive.google.com/drive/folders/1idshFvHTUfU8YIRgMRRayuRCCiMVl4WT?usp=drive_link

detection_training:
  root_dir: artifacts/detection_training

detection:
  root_dir: model/detection_n.pt
